SYMBOLS = [
    "^NSEBANK",
    "^NSEI",
    "^CNXIT",
    "RELIANCE.NS",
    "HDFCBANK.NS",
    "INFY.NS",
]

# Options - which indices to trade options on
OPTIONS_SYMBOLS = ["^NSEBANK", "^NSEI", "^CNXIT"]

STARTING_CAPITAL = 5000
MAX_POSITIONS = 3
BUFFER_CASH = 500
OPTIONS_CAPITAL = 2000
OPTIONS_STOP_PCT = 0.40
OPTIONS_TRAIL_PCT = 0.30
OPTIONS_ENABLED = True

BREAKOUT_PERIODS = 15
RSI_OVERBOUGHT = 65
RSI_OVERSOLD = 40
MIN_SIGNAL_SCORE = 5

PROFIT_TARGET = 0.01
STOP_LOSS = 0.005
TRAIL_PCT = 0.003
MAX_LOSS_PER_DAY = 500

MARKET_OPEN = "09:15"
MARKET_CLOSE = "15:30"
TRADING_END = "14:30"

PAPER_TRADE = False
BROKER = "UPSTOX"
AB_TEST_ENABLED = True

BOT_NAME = "Intra Gini"
BOT_EMOJI = "🔥"
